#!/bin/bash
# 

****************************************************************
## Start Timer :
START=$(date +%s)

# sync, build source and install builder
cd ~/android/utilitaire/linaro/linaro-crosstool/linaro_crosstool-ng
git status && git pull
make && make install
# build a15 toolchain for s4
ct-ng linaro-arm-cortex_a15-linux-gnueabihf-4.9
ct-ng build.4
# build a9 toolchain for s2
ct-ng linaro-arm-cortex_a9-linux-gnueabihf-4.9
ct-ng build.4
# build a8 toolchain for s1
ct-ng linaro-arm-cortex_a8-linux-gnueabi-4.9
ct-ng build.4
#open output directory
nautilus /android/utilitaire/linaro/linaro-crosstool/linaro_crosstool-ng/builds

#****************************************************************
## Report Timer :
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}ELAPSED: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC