#!/bin/bash

#cd /home/iyahman/android/rom/devil
#git clone -b cm-10.2 git://github.com/DerTeufel/samsung-kernel-aries
#cd /home/iyahman/android/rom/devil/samsung-kernel-aries
#git pull
#patch -p1 < patch-3.0.88-89
cd /home/iyahman/android/rom/devil/samsung-kernel-aries
make cyanogenmod_galaxysbmtd_defconfig
export ARCH=arm
#export CROSS_COMPILE=~/android/linaro/linaro-toolchains/bin/arm-cortex_a8-linux-gnueabi-
export CROSS_COMPILE=/home/iyahman/android/rom/devil/samsung-kernel-aries/toolchain/bin/arm-linux-gnueabihf-
make mrproper
export ARCH=arm
#export CROSS_COMPILE=~/android/linaro/linaro-toolchains/bin/arm-cortex_a8-linux-gnueabi-
export CROSS_COMPILE=/home/iyahman/android/rom/devil/samsung-kernel-aries/toolchain/bin/arm-linux-gnueabihf-
./mine.sh i9000
#make clean
#make mrproper

#****************************************************************
## use devil kernel :
#cp -ravu ~/android/rom/iyahmanrom10.2/kernel/samsung/aries/* ~/android/rom/originalkernel
#cd /home/iyahman/android/rom/devil/samsung-kernel-aries
#git pull
#cp -ravu ~/android/rom/devil/samsung-kernel-aries/* ~/android/rom/iyahmanrom10.2/kernel/samsung/aries
#cd ~/android/rom/iyahmanrom10.2/kernel/samsung/aries
#make mrproper

#****************************************************************
## config compiler for cyanogen kernel :
#if echo 'USE CUSTOM TOOLCHAIN FOR CYANOGEN KERNEL'
#then 
#cd ~/android/rom/iyahmanrom10.2/kernel/samsung/aries
#make cyanogenmod_galaxysbmtd_defconfig
#build envsetup
#export ARCH=arm
#export CROSS_COMPILE=~/android/linaro/linaro-toolchains/bin/arm-cortex_a8-linux-gnueabi-
#echo 'USE CUSTOM TOOLCHAIN FOR CYANOGEN KERNEL DONE'
#else read
#fi
#./build.sh galaxysmtd

#****************************************************************
## Save cyanogenkernel in zip :
#cd ~/android/rom/buildtemporaire/IyahmanRom10.2Extract/
#cp boot.img ~/android/rom/ossaturekernel
#cd ~/android/rom/ossaturekernel
#zip -qr ../cyanogenkernel4.3.zip ./
#mv cyanogenkernel4.3.zip /home/iyahman/Bureau

#****************************************************************
## restaure cyanogen kernel :
#rm -r ~/android/rom/iyahmanrom10.2/kernel/samsung/aries/*
#cp -ravu ~/android/rom/originalkernel/* ~/android/rom/iyahmanrom10.2/kernel/samsung/aries/

#****************************************************************
## clean step :
#cd ~/android/rom/iyahmanrom10.2/kernel/samsung/aries
#make mrproper
