#!/bin/bash
# 

#****************************************************************
## Start Timer :
START=$(date +%s)
#****************************************************************

export OUT_DIR_COMMON_BASE=/media/iyahman/90ceb06a-8e7e-4c74-9aad-66fc1319ccd9/home/iyahman/Bureau/outputbuildcm11

#Compil all IyahmanRom :
# iyah11 s1 linaro
# for testing..
cd /home/iyahman/android/rom/iyahmanrom11.0
. build/envsetup.sh && brunch galaxysmtd
iyah11 s2 linaro
cd /home/iyahman/android/rom/iyahmanrom11.0
#. build/envsetup.sh && brunch galaxysmtd
# . build/envsetup.sh && brunch i9100
. build/envsetup.sh && brunch i9300
#. build/envsetup.sh && brunch jflte

iyah11 s4 linaro
# iyah12 s4 linaro
# iyah12.1 s4 linaro

#****************************************************************
## Report Timer :
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}ELAPSED: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC