#!/bin/bash

#****************************************************************
## Start Timer :
START=$(date +%s)

#****************************************************************
## Start Total Timer :
DATE_START=$(date +"%s")

#****************************************************************
## Set Basic Parameters :

#set -xv

case "$1" in
        s1)
            VARIANT="galaxysmtd"
            VER="s1"
            ;;

        s2)
            VARIANT="i9100"
            VER="s2"
            ;;
            
        s4)
            VARIANT="jflte"
            VER="s4"
            ;;
esac

function timer {
    END=$(date +%s)
    ELAPSED=$((END - START))
    E_MIN=$((ELAPSED / 60))
    E_SEC=$((ELAPSED - E_MIN * 60)) echo
    printf "${txtgrn}ELAPSED: "
    [ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
    printf "%d sec(s)\n ${txtrst}" $E_SEC && echo
}

#****************************************************************
## Script speech:
echo -e "\e[31;42m 'HELLO IYAHMAN' \e[0m"
echo -e "\e[31;42m  LAUNCH IYAHMANROM V4.0 FOR $VARIANT BUILD SCRIPT: CM11.0, CUSTOM COMPILER, GAPPS WITH CUSTOM APK,'HOST AND GPS CONF' \e[0m"

#****************************************************************
## Variant selection verification:
if [ "$VARIANT" != "galaxysmtd" ] && [ "$VARIANT" != "i9100" ] && [ "$VARIANT" != "jflte" ] ; then spd-say 'bug' && echo -e "\e[31;42m  '############################################################################################################################'
echo '###################################################### PAS DE VARIANTE SELECTIONNÉE ######################################################' 
echo '############################################################################################################################' \e[0m" && read && exit
else echo
fi

#****************************************************************
## Open ccache and cpu monitor:
#cache
#gnome-system-monitor

#****************************************************************
##Use Gcc cyanogen:
# echo -e "\e[31;42m 'REINSTALL CYANOGEN GCC' \e[0m"
#if rm -rv ~/android/rom/iyahmanrom11.0/prebuilts/gcc/linux-x86/arm/* &&
#cp -rfavu ~/android/cyanogengcc/* ~/android/rom/iyahmanrom11.0/prebuilts/gcc/linux-x86/arm/
#then echo -e "\e[31;42m 'REINSTALL CYANOGEN GCC DONE' \e[0m"
#else read
#fi

#****************************************************************
##Update android SDK:
#android list sdk
#android update sdk --no-ui

#****************************************************************
##Installclean : Wipe out the stuff that changes from one make target to another.
# echo 'INSTALLCLEAN'
if cd ~/android/rom/iyahmanrom11.0/ &&
make installclean ; then timer && echo -e "\e[31;42m 'INSTALLCLEAN DONE' \e[0m"
else timer && spd-say 'bug' && echo -e "\e[31;42m 'INSTALLCLEAN FAILED' \e[0m" && read
fi

#****************************************************************
##Make Clobber : deletes all the object files AND the intermediate dependency files generated which specify the dependencies of the cpp files.
#if echo -e "\e[31;42m 'MAKE CLOBBER' \e[0m" &&
#cd ~/android/rom/iyahmanrom11.0/ && make clobber ; then
#echo -e "\e[31;42m 'MAKE CLOBBER DONE' \e[0m" &&
#. build/envsetup.sh && breakfast $VARIANT &&
#adb root && sleep 3s &&
#cd ~/android/rom/iyahmanrom11.0/device/samsung/$VARIANT/ &&
#./extract-files.sh &&
#cp -rfavu ~/android/extractedfiles/$VARIANT ~/android/rom/iyahmanrom11.0/device/samsung
#~/android/rom/iyahmanrom11.0/vendor/cm/get-prebuilts; else read
#fi
#cd ~/android/rom/iyahmanrom11.0/vendor/cm/config
#sed -i 's/$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date -u +%Y%m%d)-$(CM_BUILDTYPE)$(CM_EXTRAVERSION)-$(CM_BUILD)/IyahmanRom11.0/g' common.mk
#then echo -e "\e[31;42m 'REINSTALL AFTER CLOBBER DONE' \e[0m"

#****************************************************************
## Save extracted files :
#if adb root
#then mkdir ~/android/extractedfiles/$VARIANT
#cd ~/android/extractedfiles/$VARIANT/
#sleep 3s
#./extract-files.sh ; else read
#fi

#****************************************************************
##Remove Previous Kernel Build :
if [ "$VARIANT" = "galaxysmtd" ] ; then echo -e "\e[31;42m 'REMOVING PREVIOUS BUILD IN semaphore/output/' \e[0m"
cd ~/android/rom/semaphore/11.0/output/galaxys
cp -rfavu IyahmanKernels.zip IyahmanKernelsOld.zip
cp -rfavu IyahmanKernels.tar IyahmanKernelsOld.tar
rm -rfv IyahmanKernels.zip
rm -rfv IyahmanKernels.tar
echo -e "\e[31;42m 'REMOVING PREVIOUS BUILD IN semaphore/output/  DONE' \e[0m"
fi

#****************************************************************
## Clean buildtemporaire:
echo -e "\e[31;42m 'CLEANING TEMPORALY FILE' \e[0m"
cd ~/android/rom/buildtemporaire
rm -rfv IyahmanRom11.0Extract
rm -rfv gapps11.0Extract
rm -rfv gapps11.0.zip
rm -rfv bootanimationExtract
rm -rfv bootanimation.zip
if [ "$VARIANT" = "galaxysmtd" ] ; then
rm -rfv IyahmanKernelExtract
rm -rfv IyahmanKernels.zip
rm -rfv modemril.zip
rm -rfv modemrilExtract
rm -rfv patch720p4.4Extract
rm -rfv patch720p4.4.zip
fi ; echo -e "\e[31;42m 'CLEANING TEMPORALY FILE DONE' \e[0m"

#****************************************************************
##Synchronization, remove vendor sync and modify common.mk by IyahmanRom11.0 :
echo -e "\e[31;42m 'SYNCHRONIZATION' \e[0m"
if cd ~/android/rom/iyahmanrom11.0/ &&
#curl https://dl-ssl.google.com/dl/googlesource/git-repo/repo > ~/bin/repo
#chmod a+x ~/bin/repo
#repo init -u git://github.com/CyanogenMod/android.git -b cm-11.0
#echo -e "\e[31;42m 'repo init -u git://github.com/CyanogenMod/android.git -b cm-11.0 done'
repo selfupdate && repo sync -j16
then timer && echo -e "\e[31;42m 'REPO SYNC -j16 DONE' \e[0m"
else 
      if echo -e "\e[31;42m 'REPO SYNC -j16 FAILED, RETRY..' \e[0m" && read ; then 
      rm -rfv ~/android/rom/iyahmanrom11.0/vendor/cm/config/common.mk &&
      repo sync -j16 && ~/android/rom/iyahmanrom11.0/vendor/cm/get-prebuilts &&
      cd ~/android/rom/iyahmanrom11.0/vendor/cm/config &&
      sed -i 's/$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date -u +%Y%m%d)-$(CM_BUILDTYPE)$(CM_EXTRAVERSION)-$(CM_BUILD)/IyahmanRom11.0/g' common.mk &&
      echo -e "\e[31;42m 'REPO SYNC DONE' \e[0m"
      else echo -e "\e[31;42m 'REPO SYNC FAILED AGAIN' \e[0m" && timer && read
      fi
fi

#****************************************************************
##Save Gcc:
cp -rfavu ~/android/rom/iyahmanrom11.0/prebuilts/gcc/linux-x86/arm/* ~/android/cyanogengcc

#****************************************************************
##Use Gcc Linaro 4.8: put linaro 4.8 on cyanogen prebuilts
#cd ~/android/linaro/gcc-linaro
#bunzip2 *.tar.bz2
#tar -xvf *.tar
#rm -rfv *.tar
#rm -rfv ~/android/rom/iyahmanrom11.0/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.6/*
#rm -rfv ~/android/rom/iyahmanrom11.0/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6/*
#cp -rfavu ~/android/linaro/gcc-linaro/android-toolchain-eabi/* ~/android/rom/iyahmanrom11.0/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6
#cp -rfavu ~/android/linaro/gcc-linaro/android-toolchain-eabi/* ~/android/rom/iyahmanrom11.0/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.6
#rm -rfv ~/android/rom/iyahmanrom11.0/prebuilts/gcc/linux-x86/arm/*

#****************************************************************
## config compiler for cyanogen kernel :
#if echo -e "\e[31;42m 'USE CUSTOM TOOLCHAIN FOR CYANOGEN KERNEL'  \e[0m" &&
#cd ~/android/rom/iyahmanrom11.0/kernel/samsung/aries &&
#make mrproper &&
#echo "CONFIG_S5P_HUGEMEM=y" >> .config &&
#export ARCH=arm &&
#export CROSS_COMPILE=~/android/linaro/linaro-toolchains/bin/arm-cortex_a8-linux-gnueabi- 
#then echo -e "\e[31;42m 'USE CUSTOM TOOLCHAIN FOR CYANOGEN KERNEL DONE' \e[0m"
#else read
#fi

#****************************************************************
##Add Cherry Pick :

#****************************************************************
##replace original system syze by Iyah 
#if [ "$VARIANT" = "galaxysmtd" ] ; then cd ~/android/rom/iyahmanrom11.0/device/samsung/aries-common
#sed -i 's/629145600/304087040/g' updater.sh ; fi

#****************************************************************
##Build CM10 :
if echo -e "\e[31;42m 'BUILD CM11.0 ROM' \e[0m" &&
cd ~/android/rom/iyahmanrom11.0/ &&
export USE_CCACHE=1 && . build/envsetup.sh && brunch $VARIANT ; then
timer && echo -e "\e[31;42m 'BUILD CM11.0 ROM DONE' \e[0m"
elif echo -e "\e[31;42m '############################################################################################################################' &&
echo '###################################################### DEBUGGING TIME ######################################################' &&
echo '############################################################################################################################' \e[0m" && read &&
make clean && export USE_CCACHE=1 && . build/envsetup.sh && brunch $VARIANT
then timer && echo -e "\e[31;42m 'BUILD CM11.0 ROM DONE' \e[0m"
elif rm -rfv ~/android/rom/iyahmanrom11.0/out/target/product/$VARIANT &&
make clean && export USE_CCACHE=1 && . build/envsetup.sh && brunch $VARIANT
then timer && echo -e "\e[31;42m 'BUILD CM11.0 ROM DONE' \e[0m" ; else spd-say 'bug' && echo timer  
echo -e "\e[31;42m '############################################################################################################################'
echo '###################################################### ROM INTERVENTION MANUEL REQUISE ######################################################' 
echo '############################################################################################################################' \e[0m" && read
fi

#****************************************************************
##Build Semaphore :
if [ "$VARIANT" = "galaxysmtd" ] && echo  -e "\e[31;42m'BUILD IYAHMANKERNEL' \e[0m" && 
cd /home/iyahman/android/rom/semaphore/11.0/samsung-kernel-aries/ &&
#cp -rfavu /home/iyahman/android/rom/iyahmanrom11.0/out/target/product/$VARIANT/recovery/root/sbin/recovery /home/iyahman/android/rom/semaphore/ics-ramdisk/jb_combo/ics_rec_init/sbin/
export USE_CCACHE=1 && ./sbuild.sh galaxys s ; then timer && echo -e "\e[31;42m 'BUILD IYAHMANKERNEL DONE' \e[0m"
elif echo -e "\e[31;42m '############################################################################################################################'&&
echo '###################################################### DEBUGGING TIME ######################################################' &&
echo '############################################################################################################################' \e[0m" && read &&
make mrproper && export USE_CCACHE=1 && ./sbuild.sh galaxys s ; then timer && echo -e "\e[31;42m 'BUILD IYAHMANKERNEL DONE' \e[0m"
else spd-say 'bug' && echo -e "\e[31;42m '############################################################################################################################'
echo '###################################################### KERNEL INTERVENTION MANUEL REQUISE ######################################################' 
echo '############################################################################################################################' \e[0m" && read
fi

#****************************************************************
## Save Unofficial Nightly :
if echo -e "\e[31;42m 'SAVE UNOFFICIAL NIGHTLY' \e[0m" &&
cd ~/android/rom/iyahmanrom11.0/out/target/product/$VARIANT/ &&
cp -rfavu cm-IyahmanRom11.0.zip cm-11.0-`date -I`-UNOFFICIAL-$VARIANT.zip
then echo -e "\e[31;42m 'SAVE UNOFFICIAL NIGHTLY DONE' \e[0m"
else read
fi

#****************************************************************
## Move Rom And Extra Feature Into Temporaly Folder :
echo -e "\e[31;42m 'MOVING ROM, GAPPS INTO TEMPORALY FOLDER' \e[0m"
cd ~/android/rom/iyahmanrom11.0/out/target/product/$VARIANT/
mv -fv cm-IyahmanRom11.0.zip ~/android/rom/buildtemporaire
cd /home/iyahman/Bureau/
cp -rfavu gapps11.0.zip ~/android/rom/buildtemporaire
cp -rfavu bootanimation.zip ~/android/rom/buildtemporaire
if [ "$VARIANT" = "galaxysmtd" ] ; then
cd /home/iyahman/Bureau/
cp -rfavu patch720p4.4.zip ~/android/rom/buildtemporaire
cd /home/iyahman/android/rom/semaphore/11.0/output/galaxys
cp -rfavu IyahmanKernels.zip ~/android/rom/buildtemporaire
cp -rfavu modemril.zip ~/android/rom/buildtemporaire
fi
echo -e "\e[31;42m 'MOVING ROM, GAPP INTO TEMPORALY FOLDER DONE' \e[0m"

#****************************************************************
## unzip Rom And Extra Feature Into Respective Temporaly Folder :
echo -e "\e[31;42m 'UNZIPPING ROM, GAPPS INTO TEMPORALY FOLDER' \e[0m"
cd ~/android/rom/buildtemporaire/
unzip -q cm-IyahmanRom11.0 -d IyahmanRom11.0Extract
echo 'unzip -q cm-IyahmanRom11.0 -d IyahmanRom11.0Extract done'
unzip -q gapps11.0 -d gapps11.0Extract
echo 'unzip -q gapps11.0 -d gapps11.0Extract done'
#unzip -q bootanimation -d bootanimationExtract
#echo 'unzip -q bootanimation -d bootanimationExtract done'
if [ "$VARIANT" = "galaxysmtd" ] ; then
unzip -q patch720p4.4 -d patch720p4.4Extract
echo 'unzip -q patch720p4.4 -d patch720p4.4Extract done'
unzip -q IyahmanKernels -d IyahmanKernelExtract
echo 'unzip -q IyahmanKernels -d IyahmanKernelExtract done'
unzip -q modemril -d modemrilExtract
echo 'unzip -q modemril -d modemrilExtract done'
fi
echo -e "\e[31;42m 'UNZIPPING ROM, GAPPS INTO TEMPORALY FOLDER DONE' \e[0m"

#****************************************************************
## Save cyanogenkernel in zip :
if [ "$VARIANT" = "galaxysmtd" ] ; then
cd ~/android/rom/buildtemporaire/IyahmanRom11.0Extract/ &&
cp -rfavu boot.img ~/android/rom/ossaturekernel &&
cd ~/android/rom/ossaturekernel &&
zip -qrv ../cyanogenkernel4.4.zip ./ &&
cd ~/android/rom &&
mv -fv cyanogenkernel4.3.zip ~/android/rom/iyahmanrom11.0/out/target/product/$VARIANT/
else read
fi

#****************************************************************
## Copy Extra Feature Into Rom Temporaly Folder :
echo -e "\e[31;42m 'COPYING GAPPS PATCH720P ROMPHORE INTO TEMPORALY IYAHMANROM FOLDER' \e[0m"
cd ~/android/rom/buildtemporaire/
cp -rfavu gapps11.0Extract/* IyahmanRom11.0Extract
#cp -rfavu bootanimationExtract/system/media/bootanimation.zip IyahmanRom11.0Extract/system/media
if [ "$VARIANT" = "galaxysmtd" ] ; then
cp -rfavu patch720p4.4Extract/system/* IyahmanRom11.0Extract/system
cp -rfavu IyahmanKernelExtract/boot.img IyahmanRom11.0Extract
cp -rfavu modemrilExtract/modemril/* IyahmanRom11.0Extract
fi
echo -e "\e[31;42m 'COPYING GAPPS INTO TEMPORALY IYAHMANROM FOLDER DONE' \e[0m"

#****************************************************************
## Delete Unwanted Apk :
echo -e "\e[31;42m 'DELETING UNWANTED STUFF' \e[0m"
cd ~/android/rom/buildtemporaire/IyahmanRom11.0Extract/system/app/
if [ "$VARIANT" != "jflte" ] ; then
#dualboot apks
rm -rfv com.github.chenxiaolong.dualbootpatcher.apk
rm -rfv com.github.chenxiaolong.dualbootswitcher.apk
fi
if [ "$VARIANT" != "galaxysmtd" ] ; then
#semaphoremanager apk
rm -rfv com.semaphore.sm.apk
#bln pro apk
rm -rfv neldar.bln.control.pro.apk
#voodoo soud apk
rm -rfv org.projectvoodoo.controlapp.apk
cd ~/android/rom/buildtemporaire/IyahmanRom11.0Extract/system/lib/
rm -rfv libvoodoo-sound.so
rm -rfv libvoodoo-daemon-tools.so
rm -rfv libvoodoo-kaudio.so
fi
cd ~/android/rom/buildtemporaire/IyahmanRom11.0Extract/system/app/
if [ "$VARIANT" = "galaxysmtd" ] ; then
#dsp manager
rm -rfv DSPManager.apk
fi
# dictionnaire clavier android
rm -rfv LatinIME.apk
#apollo
rm -rfv Apollo.apk
#black hole
rm -rfv Galaxy4.apk
#boite à outils SIM
rm -rfv Stk.apk
#Bulles
rm -rfv NoiseField.apk
#calculatrice
rm -rfv Calculator.apk
#Holospiral
rm -rfv HoloSpiralWallpaper.apk
#CM file manager
rm -rfv CMFileManager.apk
#magic smoke wallpaper
rm -rfv MagicSmokeWallpapers.apk
#movie studio
rm -rfv VideoEditor.apk
#navigateur
rm -rfv Browser.apk
#quicksearhbox
rm -rfv QuickSearchBox.apk
#phase beam
rm -rfv PhaseBeam.apk
# Gallery cm11
rm -rfv Gallery2.apk
# camera cm11
rm -rfv Camera2.apk
cd ~/android/rom/buildtemporaire/IyahmanRom11.0Extract/system/priv-app/
#cm updater
rm -rfv CMUpdater.apk
#pico tts
rm -rfv PicoTts.apk
#reconnaissance vocal
rm -rfv VoiceDialer.apk
#trebuchet
rm -rfv Trebuchet.apk
cd ~/android/rom/buildtemporaire/IyahmanRom11.0Extract/system/tts/
rm -rfv lang_pico
echo -e "\e[31;42m 'DELETING UNWANTED STUFF DONE' \e[0m"

#****************************************************************
## Zip Rom In Temporaly Folder:
if echo -e "\e[31;42m 'ZIPPING IYAHMANROM' \e[0m" && 
cd ~/android/rom/buildtemporaire/ &&
rm -rfv cm-IyahmanRom11.0.zip &&
cd IyahmanRom11.0Extract &&
zip -qrv ../cm-IyahmanRom11.0.zip ./ ; then
echo -e "\e[31;42m 'ZIPPING IYAHMANROM DONE' \e[0m"
fi

#****************************************************************
## Move rom To Final Folder :
if echo -e "\e[31;42m 'MOVING IYAHMANROM INTO FINAL DIRECTORY' \e[0m" &&
cd ~/android/rom/buildtemporaire/ &&
mv -rfv cm-IyahmanRom11.0.zip ~/android/rom/iyahmanrom11.0/out/target/product/$VARIANT/
then echo -e "\e[31;42m 'MOVING IYAHMANROM INTO FINAL DIRECTORY DONE' \e[0m" ; else read
fi

#****************************************************************
## Rename Rom :
if echo -e "\e[31;42m 'RENAMING BUILD' \e[0m" && 
cd ~/android/rom/iyahmanrom11.0/out/target/product/$VARIANT/ &&
mv -rfv cm-IyahmanRom11.0.zip IyahmanRom11.0$VER-`date -I`.zip
then echo -e "\e[31;42m 'RENAMING BUILD DONE' \e[0m" ; else read 
fi

#****************************************************************
## Dual Boot :
if [ "$VARIANT" = "jflte" ] && echo -e "\e[31;42m 'PATCH FOR DUALBOOT I9505' \e[0m" ; then cd ~/android/rom/iyahmanrom11.0/out/target/product/jflte/ &&
cp -f IyahmanRom11.0$VER-`date -I`.zip cm-11-`date -u +%Y%m%d`-NIGHTLY-jflte.zip &&
cd ~/android/DualBootPatcher &&
./patch-file.sh /home/iyahman/android/rom/iyahmanrom11.0/out/target/product/$VARIANT/cm-11-`date -u +%Y%m%d`-NIGHTLY-jflte.zip &&
cd ~/android/rom/iyahmanrom11.0/out/target/product/$VARIANT/ &&
mv -f cm-11-`date -u +%Y%m%d`-NIGHTLY-jflte_dualboot.zip IyahmanRom11.0$VER-`date -I`"_dualboot".zip &&
rm -f cm-11-`date -u +%Y%m%d`-NIGHTLY-jflte.zip && timer &&
echo -e "\e[31;42m 'PATCH FOR DUALBOOT I9505 DONE' \e[0m" ; else read
fi

#****************************************************************
## Sign cm-IyahmanRom11.0 :
if echo -e "\e[31;42m 'SIGNING ZIP' \e[0m" && cd ~/android/rom/iyahmanrom11.0/out/target/product/$VARIANT/ &&
openssl pkcs8 -in /home/iyahman/android/rom/iyahmanrom11.0/build/target/product/security/testkey.pk8 -inform DER -nocrypt &&
java -Xmx2048m -jar /home/iyahman/android/rom/iyahmanrom11.0/out/host/linux-x86/framework/signapk.jar -w ~/android/rom/iyahmanrom11.0/build/target/product/security/testkey.x509.pem ~/android/rom/iyahmanrom11.0/build/target/product/security/testkey.pk8 IyahmanRom11.0$VER-`date -I`.zip IyahmanRom11.0$VER-`date -I`-signed.zip
then timer && echo -e "\e[31;42m 'SIGNING ZIP DONE' \e[0m" ; else read
fi
if [ "$VARIANT" = "jflte" ] && echo -e "\e[31;42m 'SIGNING ZIP' \e[0m" &&
cd ~/android/rom/iyahmanrom11.0/out/target/product/$VARIANT/ &&
openssl pkcs8 -in /home/iyahman/android/rom/iyahmanrom11.0/build/target/product/security/testkey.pk8 -inform DER -nocrypt &&
java -Xmx2048m -jar /home/iyahman/android/rom/iyahmanrom11.0/out/host/linux-x86/framework/signapk.jar -w ~/android/rom/iyahmanrom11.0/build/target/product/security/testkey.x509.pem ~/android/rom/iyahmanrom11.0/build/target/product/security/testkey.pk8 IyahmanRom11.0$VER-`date -I`"_dualboot".zip IyahmanRom11.0$VER-`date -I`"_dualboot"-signed.zip
then timer && echo -e "\e[31;42m 'SIGNING DUALBOOT ZIP DONE' \e[0m" ; else read
fi

#****************************************************************
## Zipalign cm-IyahmanRom11.0 :
if echo -e "\e[31;42m 'ZIPALIGNING' \e[0m" &&
cd ~/android/sdk/tools/ &&
#zipalign -c -v 4 ~/android/rom/iyahmanrom11.0/out/target/product/$VARIANT/IyahmanRom11.0$VER-`date -I`-signed.zip
zipalign -f -v 4 ~/android/rom/iyahmanrom11.0/out/target/product/$VARIANT/IyahmanRom11.0$VER-`date -I`-signed.zip ~/android/rom/iyahmanrom11.0/out/target/product/$VARIANT/IyahmanRom11.0$VER-`date -I`-signed-zipaligned.zip
then timer && echo -e "\e[31;42m 'ZIPALIGNING DONE' \e[0m" ; else read
fi
if [ "$VARIANT" = "jflte" ] && cd ~/android/sdk/tools/ &&
#zipalign -c -v 4 ~/android/rom/iyahmanrom11.0/out/target/product/$VARIANT/IyahmanRom11.0$VER-`date -I`"_dualboot".zip
zipalign -f -v 4 ~/android/rom/iyahmanrom11.0/out/target/product/$VARIANT/IyahmanRom11.0$VER-`date -I`"_dualboot"-signed.zip ~/android/rom/iyahmanrom11.0/out/target/product/$VARIANT/IyahmanRom11.0$VER-`date -I`"_dualboot"-signed-zipaligned.zip
then timer && echo -e "\e[31;42m 'ZIPALIGNING  DUALBOOT DONE' \e[0m" ; else read
fi

#****************************************************************
## Clean buildtemporaire:
echo -e "\e[31;42m 'CLEANING TEMPORALY FILE' \e[0m"
cd ~/android/rom/buildtemporaire/
rm -rf IyahmanRom11.0Extract
rm -rf cm-IyahmanRom11.0.zip
rm -rf gapps11.0Extract
rm -rf gapps11.0.zip
rm -rf bootanimationExtract
rm -rf bootanimation.zip
cd ~/android/rom/iyahmanrom11.0/out/target/product/$VARIANT/
rm -rf cm-IyahmanRom11.0.zip.md5sum
if [ "$VARIANT" = "galaxysmtd" ] ; then
rm -rf patch720p4.4Extract
rm -rf patch720p4.4.zip
rm -rf IyahmanKernelExtract
rm -rf IyahmanKernels.zip
rm -rf modemril.zip
rm -rf modemrilExtract
cd ~/android/rom/semaphore/11.0/output/galaxys
rm -rf IyahmanKernelsOld.zip
rm -rf IyahmanKernelsOld.tar
fi
echo -e "\e[31;42m 'CLEANING TEMPORALY FILE DONE' \e[0m"
echo -e "\e[31;42m '############################################################################################################################' \e[0m"
echo -e "\e[31;42m '###################################################### BUILD TERMINÉ ######################################################' \e[0m"
echo -e "\e[31;42m '############################################################################################################################' \e[0m"

#****************************************************************
## Report TOTAL timer:
DATE_END=$(date +"%s")
echo
DIFF=$(($DATE_END - $DATE_START))
echo {CM11.0 POUR $VARIANT FINI EN} "$(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds."

#****************************************************************
## Open Final Build Directory:
spd-say 'BUILD SUCCESFULL' && nautilus ~/android/rom/iyahmanrom11.0/out/target/product/$VARIANT/

bash -c "sleep 5m; pm-suspend-hybrid"
#exit
