#!/bin/bash
# 

#****************************************************************
## Start Timer :
START=$(date +%s)
#****************************************************************
#Compil all IyahmanRom :
# recocm12.1 s4
# recophilz12.1 s4
# iyah11 s1 linaro
# iyah11 s2 linaro
# iyah11 s4 linaro
makegapps
iyah12.1 s4 linaro
iyah12.1 s2 linaro
# omniall
# cd /media/iyahman/ubuntu2dd/iyahmanrom13
# repo sync -cj8 --force-sync
# . build/envsetup.sh && breakfast i9100 && brunch i9100
# . build/envsetup.sh && breakfast jfltexx && brunch jfltexx

#****************************************************************
## Report Timer :
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}ELAPSED: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC