#!/bin/bash
date

#****************************************************************
## Start timer:
START=$(date +%s)

#****************************************************************
## sync opengapps
# cd ~/android/stuff
# git clone git@github.com:opengapps/opengapps.git

cd ~/android/stuff/opengapps
git status
git pull

# ./download_sources.sh --shallow arm
./download_sources.sh --shallow arm64

## to build all platforms and releases

# make

# to build specific
# make arm-19-aroma
# make arm-19-super
# make arm-19-pico
# make arm-22-aroma
# make arm-22-super
# make arm-22-pico
# make arm-23-pico
# make arm-23-aroma
# make arm-23-super
# make arm-25-aroma
make arm-25-pico
make arm-25-nano
make arm-25-micro
# make arm64-25-aroma
make arm64-25-pico
make arm64-25-micro
# make arm64-25-mini

nautilus /home/iyahman/android/stuff/opengapps/out

## Report timer:
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}ELAPSED: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC
echo

