#!/bin/bash

export USE_CCACHE=1

#****************************************************************
## Clean and copy recovery directory :

rm -rf ~/android/rom/iyahmanrom11.0/bootable/recovery/*
cp -ravu ~/android/PHILZCWM/philz_touch_cwm6/* ~/android/rom/iyahmanrom11.0/bootable/recovery/
cd ~/android/rom/iyahmanrom11.0
. build/envsetup.sh && make clean 

#****************************************************************
## Config and compil recovery :

if . build/envsetup.sh && lunch cm_galaxysmtd-userdebug &&
make -j4 recoveryimage ; then echo ok
else read
fi
# make -d -j4 recoveryimage

#****************************************************************
## Copy recovey binary to semaphore ramdidsk, rename build and commpil kernel :

cp -ravu ~/android/rom/iyahmanrom11.0/out/target/product/galaxysmtd/recovery/root/sbin/recovery ~/android/kernel/semaphore/11.0/ics-ramdisk/jb_combo/ics_rec_init/sbin/ && echo recovery build et envoyé dans icsramdisk

cd ~/android/kernel/semaphore/11.0/samsung-kernel-aries
sed -i 's/"IyahmanKernel"/"IyahmanKernel-philz_touch_cwm6"/g' sbuild.sh
semaphore
cd ~/android/kernel/semaphore/11.0/samsung-kernel-aries
sed -i 's/"IyahmanKernel-philz_touch_cwm6"/"IyahmanKernel"/g' sbuild.sh
rm -rf ~/android/rom/iyahmanrom11.0/bootable/recovery