#!/bin/bash

export USE_CCACHE=1

case "$1" in
        s1)
            VARIANT="galaxysmtd"
            VER="s1"
            ;;

        s2)
            VARIANT="i9100"
            VER="s2"
            ;;
                       
        s4)
            VARIANT="jflte"
            VER="s4"
            ;;
            
esac

#****************************************************************
## Initialize, clean and sync repo :

cd ~/android/rom/iyahmanrom11.0
repo sync -cj16
. build/envsetup.sh && make clean 

#****************************************************************
## Config and compil recovery :

if [ "$VARIANT" = "galaxysmtd" ] ; then 
. build/envsetup.sh && lunch cm_galaxysmtd-userdebug && mka -j4 recoveryimage
elif [ "$VARIANT" = "i9100" ] ; then 
. build/envsetup.sh && lunch cm_i9100-userdebug && mka -j4 recoveryimage
elif [ "$VARIANT" = "jflte" ] ; then 
. build/envsetup.sh && lunch cm_jflte-userdebug && mka -j4 recoveryimage
fi
# make -d -j4 recoveryimage


cd ~/android/rom/iyahmanrom11.0/out/target/product/$VARIANT
mv recovery.img recovery-"$VARIANT".img
tar -H ustar -c recovery-"$VARIANT".img > recovery-"$VARIANT".tar
md5sum -t recovery-"$VARIANT".tar >> recovery-"$VARIANT".tar
mv recovery-"$VARIANT".tar recovery-"$VARIANT".tar.md5