#!/bin/bash
date

#****************************************************************
## Start timer:
START=$(date +%s)

# #****************************************************************
# ## Prepare cm11 android 4.4.4:
# cd ~/android/rom/iyahmanrom11.0/
# repo init -u git://github.com/CyanogenMod/android.git -b cm-11.0
# echo 'repo init -u git://github.com/CyanogenMod/android.git -b cm-11.0 done'
# repo selfupdate && repo sync -j16
# . build/envsetup.sh && breakfast galaxysmtd
# . build/envsetup.sh && breakfast i9100
# . build/envsetup.sh && breakfast i9300
# . build/envsetup.sh && breakfast jflte
# ~/android/rom/iyahmanrom11.0/vendor/cm/get-prebuilts


#****************************************************************
## Prepare cm12.1 android 5.1.1:
cd ~/android/rom/iyahmanrom12.1/
repo init -u git://github.com/CyanogenMod/android.git -b cm-12.1
echo 'repo init -u git://github.com/CyanogenMod/android.git -b cm-12.1 done'
repo sync -cj16
repo selfupdate && repo sync -cj16
. build/envsetup.sh && breakfast galaxysmtd
. build/envsetup.sh && breakfast i9100
. build/envsetup.sh && breakfast i9300
. build/envsetup.sh && breakfast jfltexx
~/android/rom/iyahmanrom12.1/vendor/cm/get-prebuilts
#****************************************************************
## Prepare cm13 android 6.0:
if cd /media/iyahman/ubuntu2dd/iyahmanrom13/
then repo init -u git://github.com/CyanogenMod/android.git -b cm-13.0
     echo 'repo init -u git://github.com/CyanogenMod/android.git -b cm-13.0 done'
     repo sync -cj16
     repo selfupdate && repo sync -cj16
     . build/envsetup.sh && breakfast galaxysmtd
     . build/envsetup.sh && breakfast i9100
     . build/envsetup.sh && breakfast i9300
     . build/envsetup.sh && breakfast jfltexx
     ~/android/rom/iyahmanrom12.1/vendor/cm/get-prebuilts
else echo 'error'
fi

cd ~/android/rom/omnirom/
repo init -u https://github.com/omnirom/android.git -b android-5.1
repo sync -cj16

#****************************************************************
## Report timer:
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}ELAPSED: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC
echo

