#!/bin/bash
date

#****************************************************************
## Start timer:
START=$(date +%s)

cd ~/android/rom/iyahmanrom11.0/
repo init -u git://github.com/CyanogenMod/android.git -b cm-11.0
echo 'repo init -u git://github.com/CyanogenMod/android.git -b cm-11.0 done'
repo selfupdate && repo sync -j16
. build/envsetup.sh && breakfast galaxysmtd
. build/envsetup.sh && breakfast i9100
. build/envsetup.sh && breakfast jflte
~/android/rom/iyahmanrom11.0/vendor/cm/get-prebuilts

#****************************************************************
## Report timer:
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}ELAPSED: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC
echo
