#!/bin/bash


#****************************************************************
## Script command exemple :
#iyah $1                    iyah $1 $2
#iyah s1 || iyah s1pucca || iyah s1 linaro || iyah s1 linarof
#iyah s2 ""
#iyah s4 ""

#****************************************************************
## Start Timer :
START=$(date +%s)

#****************************************************************
## Start Total Timer :
DATE_START=$(date +"%s")

#****************************************************************
## Set Basic Parameters :
set -xv
make 2> /home/iyahman/Bureau/mesbuildscripts/Iyahmanrom/11.0/compilog

function timer {
    END=$(date +%s)
    ELAPSED=$((END - START))
    E_MIN=$((ELAPSED / 60))
    E_SEC=$((ELAPSED - E_MIN * 60))
    echo && printf "${txtgrn}ELAPSED: "
    printf "%d min(s) " $E_MIN
    printf "%d sec(s)\n ${txtrst}" $E_SEC && echo
}



ROMNAME="IyahmanRom"

case "$1" in
        s1)
            VARIANT="galaxysmtd"
            VER="s1"
            ;;

        s1pucca)
	    VARIANT="galaxysmtd"
            VER="s1"
            ROMNAME="PuccaRom"
            ;;
        s2)
            VARIANT="i9100"
            VER="s2"
            ;;
            
        s2pucca)
	    VARIANT="i9100"
            VER="s2"
            ROMNAME="PuccaRom"
            ;;
            
        s4)
            VARIANT="jflte"
            VER="s4"
            ;;
            
        s4pucca)
	    VARIANT="jflte"
            VER="s4"
            ROMNAME="PuccaRom"
            ;;
            
esac

case "$2" in
	linaro)
	    TOOLCHAIN="-linaro"
	    ;;
	    
	linarof)
	    FORCETOOLCHAIN="on"
	    ;;
	    
esac    

if [ "$3" = "slim" ] ; then
SYSTEMSIZE="on"
fi

if [ "$3" = "clean" ] ; then
MAKECLEAN="on"
fi

CMVER='11.0'
CMROMNAME=cm-11-`date -u +%Y%m%d`-UNOFFICIAL-$VARIANT

#****************************************************************
##Make Clobber : deletes all the object files AND the intermediate dependency files generated which specify the dependencies of the cpp files.
function fullcleanup {
if echo -e "\e[31;42m 'MAKE CLOBBER' \e[0m" &&
cd ~/android/rom/iyahmanrom$CMVER/ && make clobber
then echo -e "\e[31;42m 'MAKE CLOBBER DONE' \e[0m"
  if . build/envsetup.sh && breakfast $VARIANT &&
  adb root && echo -e "\e[31;42m 'WAITING TO CONNECT $VARIANT TO YOUR PC' \e[0m" && read &&
  cd ~/android/rom/iyahmanrom$CMVER/device/samsung/$VARIANT/ &&
  ./extract-files.sh &&
  ~/android/rom/iyahmanrom$CMVER/vendor/cm/get-prebuilts
  then echo -e "\e[31;42m 'REINSTALL AFTER CLOBBER DONE' \e[0m"
  else echo -e "\e[31;42m 'REINSTALL AFTER CLOBBER FAILED' \e[0m" && read
  fi
else echo -e "\e[31;42m 'MAKE CLOBBER FAILED' \e[0m" && read
fi
}

#****************************************************************
## Script speech:
echo -e "\e[31;42m 'HELLO IYAHMAN' \e[0m"
echo -e "\e[31;42m  LAUNCH $ROMNAME$CMVER$TOOLCHAIN BUILD SCRIPT V4.1 FOR $VARIANT WITH GAPPS, CUSTOM APK,'HOST AND GPS CONF' \e[0m"
sleep 1s

#****************************************************************
## Variant selection verification:
if [ "$VARIANT" != "galaxysmtd" ] && [ "$VARIANT" != "i9100" ] && [ "$VARIANT" != "jflte" ]
then spd-say 'bug' && echo -e "\e[31;42m  '############################################################################################################################'
echo '###################################################### PAS DE VARIANTE SELECTIONNÉE POUR $ROMNAME$CMVER ######################################################' 
echo '############################################################################################################################' \e[0m" && read && exit
else echo -n
fi

#****************************************************************
## Open ccache and cpu monitor:
#cache
#gnome-system-monitor

#****************************************************************
##Update android SDK:
#android list sdk
#android update sdk --no-ui

if [ "$MAKECLEAN" = "on" ] ; then 
cd ~/android/rom/iyahmanrom$CMVER/
make clean
fi

#****************************************************************
##Installclean : Wipe out the stuff that changes from one make target to another.
if echo -e "\e[31;42m 'INSTALLCLEAN' \e[0m" &&
cd ~/android/rom/iyahmanrom$CMVER/ &&
make installclean 
then timer && echo -e "\e[31;42m 'INSTALLCLEAN DONE' \e[0m"
else echo -e "\e[31;42m 'INSTALLCLEAN FAILED' \e[0m" && read
fi

#****************************************************************
## Save extracted files :
#if echo -e "\e[31;42m 'SAVE EXTRACTED FILES' \e[0m" &&
#adb root &&
#mkdir ~/android/extractedfiles/$VARIANT &&
#cd ~/android/extractedfiles/$VARIANT/ &&
#sleep 3s &&
#./extract-files.sh
#then echo -e "\e[31;42m 'SAVE EXTRACTED FILES DONE' \e[0m"
#else echo -e "\e[31;42m 'SAVE EXTRACTED FILES FAILED' \e[0m" && read
#fi

#****************************************************************
##Remove Previous Kernel Build :
if [ "$VARIANT" = "galaxysmtd" ] ; then
  if echo -e "\e[31;42m 'REMOVING PREVIOUS BUILD IN semaphore/output/' \e[0m" &&
  cd ~/android/rom/semaphore/11.0/output/galaxys &&
  cp -rfavu IyahmanKernels.zip IyahmanKernelsOld.zip &&
  cp -rfavu IyahmanKernels.tar IyahmanKernelsOld.tar &&
  rm -rfv IyahmanKernels.zip &&
  rm -rfv IyahmanKernels.tar
  then echo -e "\e[31;42m 'REMOVING PREVIOUS BUILD IN semaphore/output/  DONE' \e[0m"
  else echo -e "\e[31;42m 'REMOVING PREVIOUS BUILD IN semaphore/output/  FAILED' \e[0m" && read
  fi
fi

#****************************************************************
## Clean buildtemporaire:
if echo -e "\e[31;42m 'CLEANING TEMPORALY FILE' \e[0m" && 
rm -rfv ~/android/rom/buildtemporaire/* &&
rm -rfv ~/android/rom/iyahmanrom11.0/out/target/product/$VARIANT/cm-11-*-UNOFFICIAL-$VARIANT.zip.md5sum
then echo -e "\e[31;42m 'CLEANING TEMPORALY FILE DONE' \e[0m"
else echo -e "\e[31;42m 'CLEANING TEMPORALY FILE FAILED' \e[0m" && read
fi

#****************************************************************
##Synchronization :
if echo -e "\e[31;42m 'SYNCHRONIZATION' \e[0m" &&
cd ~/android/rom/iyahmanrom$CMVER/ &&
#curl https://dl-ssl.google.com/dl/googlesource/git-repo/repo > ~/bin/repo &&
#chmod a+x ~/bin/repo &&
#repo init -u git://github.com/CyanogenMod/android.git -b cm-$CMVER &&
#echo -e "\e[31;42m 'repo init -u git://github.com/CyanogenMod/android.git -b cm-$CMVER done' &&
repo selfupdate && repo sync -j16
then timer && echo -e "\e[31;42m 'REPO SYNC -j16 DONE ON  git://github.com/CyanogenMod/android.git -b cm-$CMVER' \e[0m"
else 
  if echo -e "\e[31;42m 'REPO SYNC -j16 FAILED ON  git://github.com/CyanogenMod/android.git -b cm-$CMVER' \e[0m" &&
  repo selfupdate && repo sync -j4
  then timer && echo -e "\e[31;42m 'REPO SYNC -j4 DONE THIS TIME ON  git://github.com/CyanogenMod/android.git -b cm-$CMVER' \e[0m"
  else echo -e "\e[31;42m 'REPO SYNC -j4 FAILED THIS TIME AGAIN ON  git://github.com/CyanogenMod/android.git -b cm-$CMVER' \e[0m" && read
  fi
fi

#****************************************************************
##Save Gcc:
if [ "$TOOLCHAIN" = "-linaro" ] && [ "$FORCETOOLCHAIN" = "on" ] ; then
  if echo -e "\e[31;42m 'SAVE CYANOGENMOD TOOLCHAIN' \e[0m" &&
  cp -rfavu ~/android/rom/iyahmanrom$CMVER/prebuilts/gcc/linux-x86/arm/* ~/android/cyanogengcc$CMVER
  then echo -e "\e[31;42m 'SAVE CYANOGENMOD TOOLCHAIN DONE' \e[0m"
  else echo -e "\e[31;42m 'SAVE CYANOGENMOD TOOLCHAIN FAILED' \e[0m" && read
  fi
fi

#****************************************************************
##Use Gcc Linaro 4.8: put linaro 4.8 on cyanogen prebuilts
if [ "$TOOLCHAIN" = "-linaro" ] && [ "$FORCETOOLCHAIN" = "on" ] ; then
  if echo -e "\e[31;42m 'REPLACE CYANOGENMOD TOOLCHAIN BY LINARO TOOLCHAIN' \e[0m" &&
  cd ~/android/linaro/gcc-linaro &&
  bunzip2 *.tar.bz2 &&
  tar -xvf *.tar &&
  rm -rfv *.tar &&
  #rm -rfv ~/android/rom/iyahmanrom$CMVER/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.6/* &&
  rm -rfv ~/android/rom/iyahmanrom$CMVER/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6/* && 
  cp -rfavu ~/android/linaro/gcc-linaro/android-toolchain-eabi/* ~/android/rom/iyahmanrom$CMVER/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6
  #cp -rfavu ~/android/linaro/gcc-linaro/android-toolchain-eabi/* ~/android/rom/iyahmanrom$CMVER/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.6
  #rm -rfv ~/android/rom/iyahmanrom$CMVER/prebuilts/gcc/linux-x86/arm/*
  then echo -e "\e[31;42m 'REPLACE CYANOGENMOD TOOLCHAIN BY LINARO TOOLCHAIN DONE' \e[0m"
  else echo -e "\e[31;42m 'REPLACE CYANOGENMOD TOOLCHAIN BY LINARO TOOLCHAIN FAILED' \e[0m" && read
  fi
fi

#****************************************************************
##Add Cherry Pick :

#****************************************************************
##replace original system syze by Iyah 
if [ "$VARIANT" = "galaxysmtd" ] && [ "SYSTEMSIZE" = "on" ] ; then
  if echo -e "\e[31;42m 'CHANGE SYSTEM SIZE' \e[0m" &&
  cd ~/android/rom/iyahmanrom$CMVER/device/samsung/aries-common &&
  sed -i 's/629145600/304087040/g' updater.sh
  then echo -e "\e[31;42m 'CHANGE SYSTEM SIZE FOR GALAXYSMTD DONE' \e[0m"
  else echo -e "\e[31;42m 'CHANGE SYSTEM SIZE FOR GALAXYSMTD FAILED' \e[0m" && read
  fi
fi

#****************************************************************
##Build CM10 :
if echo -e "\e[31;42m 'BUILD CM$CMVER ROM' \e[0m" &&
cd ~/android/rom/iyahmanrom$CMVER/ &&
. build/envsetup.sh && breakfast $VARIANT && export USE_CCACHE=1
then echo -e "\e[31;42m 'BREAKFAST CM$CMVER ROM DONE' \e[0m" &&
  if [ "$TOOLCHAIN" = "-linaro" ] && [ "$VARIANT" = "galaxysmtd" ] ; then
      if echo -e "\e[31;42m 'SET LINARO TOOLCHAIN FOR $VARIANT CYANOGEN KERNEL'  \e[0m" &&
      cd ~/android/rom/iyahmanrom$CMVER/kernel/samsung/aries && make mrproper &&
      cd ~/android/rom/iyahmanrom$CMVER/ && . build/envsetup.sh && breakfast $VARIANT &&      
      export ARCH=arm ARM_EABI_TOOLCHAIN=~/android/linaro/linaro-toolchain$VER/bin
      then echo -e "\e[31;42m 'SET LINARO TOOLCHAIN FOR $VARIANT CYANOGEN KERNEL DONE'  \e[0m"
      else echo -e "\e[31;42m 'SET LINARO TOOLCHAIN FOR $VARIANT CYANOGEN KERNEL FAILED'  \e[0m" && read
      fi
  elif [ "$TOOLCHAIN" = "-linaro" ] && [ "$VARIANT" = "i9100" ] ; then
      if echo -e "\e[31;42m 'SET LINARO TOOLCHAIN FOR $VARIANT CYANOGEN KERNEL'  \e[0m" &&
      cd ~/android/rom/iyahmanrom$CMVER/kernel/samsung/smdk4412 && make mrproper &&
      cd ~/android/rom/iyahmanrom$CMVER/ && . build/envsetup.sh && breakfast $VARIANT &&      
      export ARCH=arm ARM_EABI_TOOLCHAIN=~/android/linaro/linaro-toolchain$VER/bin
      then echo -e "\e[31;42m 'SET LINARO TOOLCHAIN FOR $VARIANT CYANOGEN KERNEL DONE'  \e[0m"
      else echo -e "\e[31;42m 'SET LINARO TOOLCHAIN FOR $VARIANT CYANOGEN KERNEL FAILED'  \e[0m" && read
      fi
  elif [ "$TOOLCHAIN" = "-linaro" ] && [ "$VARIANT" = "jflte" ] ; then 
      if echo -e "\e[31;42m 'SET LINARO TOOLCHAIN FOR $VARIANT CYANOGEN KERNEL'  \e[0m" &&
      cd ~/android/rom/iyahmanrom$CMVER/kernel/samsung/jf && make mrproper &&
      cd ~/android/rom/iyahmanrom$CMVER/ && . build/envsetup.sh && breakfast $VARIANT &&      
      export ARCH=arm ARM_EABI_TOOLCHAIN=~/android/linaro/linaro-toolchain$VER/bin
      then echo -e "\e[31;42m 'SET LINARO TOOLCHAIN FOR $VARIANT CYANOGEN KERNEL DONE'  \e[0m"
      else echo -e "\e[31;42m 'SET LINARO TOOLCHAIN FOR $VARIANT CYANOGEN KERNEL FAILED'  \e[0m" && read
      fi
  fi
else echo -e "\e[31;42m 'BREAKFAST CM$CMVER ROM FAILED' \e[0m" && read
fi

export -p && read
env && read

mka bootimage
