#!/bin/bash
# 

#****************************************************************
#sync all github repo with latest version from my source

cd ~/Bureau/mesbuildscripts && git status && git pull
cd ~/android/kernel/KT-AOSP/KT-SGS4 && git status && git pull
cd ~/android/kernel/KT-TW4.4/KT-SGS4 && git status && git pull
cd ~/android/kernel/semaphore/11.0/android_bootable_recovery && git status && git pull
cd ~/android/kernel/semaphore/11.0/android_device_samsung_aries-common && git status && git pull
cd ~/android/kernel/semaphore/11.0/ics-ramdisk && git status && git pull
cd ~/android/kernel/semaphore/11.0/samsung-kernel-aries && git status && git pull
cd ~/android/philz_touch_cwm6 && git status && git pull
cd ~/android/android_build && git status && git pull
cd ~/android/utilitaire/linaro/linaro-crosstool/linaro_crosstool-ng && git status && git pull

#****************************************************************
#sync all github repo with latest version from original source

cd ~/android/rom/proprietary_files/cm11/proprietary_vendor_samsung && git status && git pull
cd ~/android/rom/proprietary_files/cm12/proprietary_vendor_samsung && git status && git pull
cd ~/android/utilitaire/google-gcc/arm-eabi-4.8 && git status && git pull
cd ~/android/utilitaire/google-gcc/arm-linux-androideabi-4.8 && git status && git pull

#****************************************************************
#copy samsung blobs to cm directory

cp -ravu ~/android/rom/proprietary_files/cm11/proprietary_vendor_samsung/* ~/android/rom/iyahmanrom11.0/vendor/samsung
cp -ravu ~/android/rom/proprietary_files/cm12/proprietary_vendor_samsung/* ~/android/rom/iyahmanrom12.0/vendor/samsung

#****************************************************************
##Update android SDK:

#android list sdk
#android update sdk --no-ui