#!/bin/bash

#****************************************************************
## Start Timer :
START=$(date +%s)

export USE_CCACHE=1
export OUT_DIR_COMMON_BASE=/media/iyahman/90ceb06a-8e7e-4c74-9aad-66fc1319ccd9/home/iyahman/Bureau/outputbuildcm11

case "$1" in
        s1)
            VARIANT="galaxysmtd"
            VER="s1"
            ;;

        s2)
            VARIANT="i9100"
            VER="s2"
            ;;
                       
        s4)
            VARIANT="jflte"
            VER="s4"
            ;;
            
esac


cd ~/android/rom/iyahmanrom11.0
make clean
repo sync -j16
# . build/envsetup.sh && make clean

#****************************************************************
## Config and compil recovery :

if [ "$VARIANT" = "galaxysmtd" ] ; then 
. build/envsetup.sh && lunch cm_galaxysmtd-userdebug && mka -j3 recoveryimage RECOVERY_VARIANT=philz
elif [ "$VARIANT" = "i9100" ] ; then 
. build/envsetup.sh && lunch cm_i9100-userdebug && mka -j3 recoveryimage RECOVERY_VARIANT=philz
elif [ "$VARIANT" = "jflte" ] ; then 
. build/envsetup.sh && lunch cm_jflte-userdebug && mka -j3 recoveryimage RECOVERY_VARIANT=philz
fi

cd /media/iyahman/90ceb06a-8e7e-4c74-9aad-66fc1319ccd9/home/iyahman/Bureau/outputbuildcm11/iyahmanrom11.0/target/product/$VARIANT
mv recovery.img recovery-philz"$VARIANT".img
tar -H ustar -c recovery-philz"$VARIANT".img > recovery-philz"$VARIANT".tar
md5sum -t recovery-philz"$VARIANT".tar >> recovery-philz"$VARIANT".tar
mv recovery-philz"$VARIANT".tar recovery-philz"$VARIANT".tar.md5
#****************************************************************
## Report Timer :
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}ELAPSED: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC