#!/bin/bash

#****************************************************************
## Start Total Timer :
DATE_START=$(date +"%s")

cd ~/android/rom/iyahmanrom12.0
. build/envsetup.sh && breakfast jfltexx
cd ~/android/rom/iyahmanrom12.0/kernel/samsung/jf
make menuconfig KCONFIG_CONFIG=arch/arm/configs/cyanogen_jf_defconfig 
make mrproper
cd ~/android/rom/iyahmanrom12.0
make installclean
mka bootimage

#****************************************************************
## Report TOTAL timer:
DATE_END=$(date +"%s")
echo
DIFF=$(($DATE_END - $DATE_START))
echo $ROMNAME$CMVER pour $VARIANT fini en "$(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds."
