#!/bin/bash
# 

export USE_NINJA=true
export USE_CCACHE=1
#****************************************************************
## Start Timer :
START=$(date +%s)
#****************************************************************
#Compil aosp7:

cd /media/iyahman/ubuntu2dd/aosp7
repo sync -cj16 --force-sync
# repo sync -cj4 --force-sync
. build/envsetup.sh
make installclean 
find ./out/ -name 'build.prop' | xargs rm
# make clobber
# breakfast jflte
cd  /media/iyahman/ubuntu2dd/aosp7/kernel/samsung/jf
make mrproper
cd /media/iyahman/ubuntu2dd/aosp7
# brunch jflte
lunch 11
mka otapackage

## Report Timer :
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}ELAPSED: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC