#!/bin/bash
# 

#****************************************************************
## Start Timer :
START=$(date +%s)
#****************************************************************
export USE_CCACHE=1

cd ~/android/rom/Opticm13
repo selfupdate
repo sync -cj16 --force-sync
# ccache -c && ccache -z
# rm -R /media/iyahman/ubuntu2dd/ccache
# make clobber
# rm -R ~/android/rom/Opticm13/vendor/samsung/jf-common
# # cd /media/iyahman/ubuntu2dd
# # git clone -b jf-6.0-newril https://github.com/JDCTeam/proprietary_vendor_samsung.git
# cd /media/iyahman/ubuntu2dd/proprietary_vendor_samsung && git pull
# cp -R /media/iyahman/ubuntu2dd/proprietary_vendor_samsung/jf-common ~/android/rom/Opticm13/vendor/samsung
# cd ~/android/rom/Opticm13
. build/envsetup.sh
make installclean 
find ./out/ -name 'build.prop' | xargs rm
# make clobber
# breakfast jflte
# cd  ~/android/rom/Opticm13/kernel/samsung/jf
# make mrproper

cd  ~/android/rom/Opticm13/build
git fetch https://github.com/iyahman/android_build.git cm-13.0
##fr commit
git cherry-pick 3468a8d4f4a729f35b469a1870c7d8db9649c140
##use uber4.9 for arm-linux-androideabi
# git cherry-pick 4fad83fde0177738c8d1a82c1daf38b7c96777db
# ##use uber5.3 for arm-linux-androideabi
# git cherry-pick 3ed95fa169779cc47df5899dd5aca6e9db6cbda4
# ##add uber5.2 eabi for kernel
# git cherry-pick 0d091defa4c4004c5f5fe9217856235d189e5234
# ##add uber5.3 eabi for kernel and 4.9 arm-androideabi
# git cherry-pick 01600c695fc437d9b2d376bf9786f1e47eadebbc


cd ~/android/rom/Opticm13
. build.sh
# . build/envsetup.sh
# make installclean 
# find ./out/ -name 'build.prop' | xargs rm
# # breakfast jflte
# # mka bootimage
# brunch jflte
nautilus ~/android/rom/Opticm13/out/target/product/jflte


#****************************************************************
## Report Timer :
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}ELAPSED: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC
