#!/bin/bash
# 

export USE_NINJA=true
export USE_CCACHE=1
#****************************************************************
## Start Timer :
START=$(date +%s)
#****************************************************************
#Compil cm14:

cd /home/iyahman/android/rom/iyahmanrom14
repo sync -cj16 --force-sync
# repo sync -cj4 --force-sync
. build/envsetup.sh
make installclean 
find ./out/ -name 'build.prop' | xargs rm
make clobber
breakfast jfltexx
cd  /home/iyahman/android/rom/iyahmanrom14/kernel/samsung/jf
make mrproper
cd /home/iyahman/android/rom/iyahmanrom14
brunch jfltexx
# lunch 11
# mka otapackage

## Report Timer :
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}ELAPSED: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC
