#!/bin/bash
# 

#****************************************************************
## Start Timer :
START=$(date +%s)
#****************************************************************

export USE_CCACHE=1
export ANDROID_CCACHE_DIR="/media/iyahman/LINUXEXTEND/.ccache"

cd /media/iyahman/LINUXEXTEND/rom/opticm14
. build.sh
# cd /media/iyahman/LINUXEXTEND/rom/opticm14/build
# git fetch https://github.com/iyahman/android_build-1.git cm-14.1
# ##fr commit
# git cherry-pick 8a8ae476ec7f120bd563dc8332922862a509aa2f

echo 1

nautilus /media/iyahman/LINUXEXTEND/rom/opticm14


#****************************************************************
## Report Timer :
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}ELAPSED: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC
