#!/bin/bash
# 

export USE_CCACHE=0

#****************************************************************
## Start Timer :
START=$(date +%s)
#****************************************************************
#Compil cm14:

cd /run/media/iyahman/LINUXEXTEND/rom/twrpomni
repo sync -cj16 --force-sync
# repo sync -cj4 --force-sync
# . build/envsetup.sh
# make clobber
. build/envsetup.sh
lunch omni_hero2lte-eng
mka recoveryimage

## Report Timer :
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}ELAPSED: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC
